# JWT authorization example
# Run with `cargo run -p htsget-axum --all-features -- --config htsget-config/docs/examples/auth.toml`

ticket_server.addr = "127.0.0.1:8080"
data_server.addr = "127.0.0.1:8081"

locations = "file://data"

# JWT authorization configuration.
[auth]
jwks_url = "https://www.example.com/htsget"
## Alternatively use public key-based validation
#public_key = "/path/to/jwt-public-key.pem"

validate_audience = ["htsget-server"]
validate_issuer = ["https://www.example.com"]
validate_subject = "htsget"

# Authorization URLs, if using an authorization service.
authorization_url = "https://www.example.com/authorize"
# Forward the authorization header to the auth server.
passthrough_auth = true
## Any headers to forward
#forward_headers = ["Content-Type"]

## Set client authentication
#http.key = "key.pem"
#http.cert = "cert.pem"
#
## Set root certificates
#http.root_store = "root.crt"
## Disable HTTP caching
#http.use_cache = false

## It's also possible to set auth individually for the ticket and data servers:
#[ticket_server.auth]
#[data_server.auth]
