name: docker

on:
  push:
    branches:
      - main

jobs:
  docker:
    permissions:
      contents: read
      pull-requests: write
    name: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Login to GHCR.io (GH's Container Registry)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker GitHub release
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          provenance: false
          platforms: ${{ matrix.platforms }}
          push: true
          tags: |
            ghcr.io/umccr/htsget-rs:latest

## SOCI (Seekable OCI) support. Only enable when and if docker layers surpass 10MB in the future, see:
# https://github.com/awslabs/soci-snapshotter/issues/100
#      - name: Install aws SOCI
#        uses: iamops-team/aws-soci@v1.0
#      - name: Pull the image in containerd
#        run: |
#          sudo ctr i pull --user ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} ghcr.io/umccr/htsget-rs:latest
#      - name: Create and push soci index
#        run: |
#          sudo soci create ghcr.io/umccr/htsget-rs:latest
#          sudo soci push --user ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} ghcr.io/umccr/htsget-rs:latest
